#!/bin/sh
set -eu
cd "$(dirname "$0")"
report=$(bun "${BEND2_CORE:-../bend2-core}/bend2/main.ts" proofs.bend)
if [ "$report" != 'All terms check.' ]; then
  printf '%s\n' "$report" >&2
  echo 'Kernel proofs must check with no unsafe definitions, axioms, or TODOs.' >&2
  exit 1
fi
echo 'PASS original kernel, numeric, health, growth, reward, vital-state, monster, roster, AI-list, zone-conservation, player-list, tick-composition, inventory-command, kill-payout, navigation, interaction, combat-admission, battle-composition, terrain/movement, player-locomotion, seeded-landscape, monster-position, active-monster-planning, seeded-population, complete-position-tick, monster-ID-uniqueness, allocation/admission, player-ID-preservation, monster-target-reference, command-reference-preservation, authoritative-target-selection, complete-tick-reference, nonzero-player/connection-ID, combined-pure-world-state, connection-lifecycle, bidirectional-connection-roster, connection-selection, joint-player-creation, joint-disconnect, command-binding-correspondence, complete-tick-binding, bounded-allocation-success, exact-allocation-successor, complete-allocation/capacity, successful-world-reconstruction, connection-rebinding, complete-pure-restart/trace, live-channel-restart, reconstruction-metadata, and stored-seed/map/mixed-trace and live-clock-update and authoritative-tick/output and live-inventory/interaction/output and live-combat/output and combat-target-selection/planning and indexed-spin-plan and sequential-combat-frame and current-attacker and admitted-actor and live-spin-planner and live-attack-planner and completed-combat-repeat and unconditional-combat-repeat and clock-combat-repeat and finite-combat-spam and player-cooldown-upkeep and live-tick-cooldown-roster and tracked-tick-cooldown and mixed-combat-cooldown and foreign-combat-frame and arbitrary-combat-stream and partial-cooldown-tick and exact-combat-transition and mixed-live-history and quantitative-cooldown and lethal-attack-reward and lethal-spin-reward and dead-monster-reward-trace and exactly-once-lethal-reward and live-dead-reward-history and actual-lethal-attack-history and actual-lethal-spin-history and mixed-damage-spin-history and monster-lifetime-boundary and planned-zone-lifetime and actual-live-tick-lifetime and permanent-death-mixed-history and ordinary-respawn-prefix and ordinary-lifetime-once proofs'
